# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GraphicsView.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1462, 974)
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.fig1 = QtWidgets.QGraphicsView(self.centralwidget)
        self.fig1.setEnabled(True)
        self.fig1.setGeometry(QtCore.QRect(20, 250, 701, 531))
        self.fig1.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.fig1.setObjectName("fig1")
        self.segmentation_box = QtWidgets.QGroupBox(self.centralwidget)
        self.segmentation_box.setEnabled(False)
        self.segmentation_box.setGeometry(QtCore.QRect(360, 10, 171, 201))
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.segmentation_box.setFont(font)
        self.segmentation_box.setStyleSheet("font: italic 14pt \"Monotype Corsiva\";background-color: rgb(231, 144, 255);")
        self.segmentation_box.setObjectName("segmentation_box")
        self.entropymethod = QtWidgets.QRadioButton(self.segmentation_box)
        self.entropymethod.setEnabled(False)
        self.entropymethod.setGeometry(QtCore.QRect(10, 30, 151, 17))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.entropymethod.setFont(font)
        self.entropymethod.setStyleSheet("font: 75 12pt \"Times New Roman\";")
        self.entropymethod.setObjectName("entropymethod")
        self.thersholdmethod = QtWidgets.QRadioButton(self.segmentation_box)
        self.thersholdmethod.setEnabled(False)
        self.thersholdmethod.setGeometry(QtCore.QRect(10, 50, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.thersholdmethod.setFont(font)
        self.thersholdmethod.setStyleSheet("font: 75 12pt \"Times New Roman\";")
        self.thersholdmethod.setObjectName("thersholdmethod")
        self.applysegmentation = QtWidgets.QPushButton(self.segmentation_box)
        self.applysegmentation.setEnabled(False)
        self.applysegmentation.setGeometry(QtCore.QRect(90, 170, 75, 23))
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.applysegmentation.setFont(font)
        self.applysegmentation.setStyleSheet("color: rgb(0, 0, 0);font: italic 14pt \"Monotype Corsiva\";background-color: rgb(231, 194, 255);")
        self.applysegmentation.setObjectName("applysegmentation")
        self.segmentationbar = QtWidgets.QSlider(self.segmentation_box)
        self.segmentationbar.setEnabled(False)
        self.segmentationbar.setGeometry(QtCore.QRect(40, 100, 91, 22))
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.segmentationbar.setFont(font)
        self.segmentationbar.setOrientation(QtCore.Qt.Horizontal)
        self.segmentationbar.setObjectName("segmentationbar")
        self.seg1 = QtWidgets.QLabel(self.segmentation_box)
        self.seg1.setEnabled(False)
        self.seg1.setGeometry(QtCore.QRect(10, 100, 20, 21))
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.seg1.setFont(font)
        self.seg1.setObjectName("seg1")
        self.seg2 = QtWidgets.QLabel(self.segmentation_box)
        self.seg2.setEnabled(False)
        self.seg2.setGeometry(QtCore.QRect(140, 100, 31, 16))
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.seg2.setFont(font)
        self.seg2.setObjectName("seg2")
        self.manualsegmentation = QtWidgets.QPushButton(self.segmentation_box)
        self.manualsegmentation.setEnabled(False)
        self.manualsegmentation.setGeometry(QtCore.QRect(10, 170, 75, 23))
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.manualsegmentation.setFont(font)
        self.manualsegmentation.setStyleSheet("color: rgb(0, 0, 0);font: italic 14pt \"Monotype Corsiva\";background-color: rgb(231, 194, 255);")
        self.manualsegmentation.setObjectName("manualsegmentation")
        self.label_pre_2 = QtWidgets.QLabel(self.segmentation_box)
        self.label_pre_2.setEnabled(False)
        self.label_pre_2.setGeometry(QtCore.QRect(10, 140, 161, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_pre_2.setFont(font)
        self.label_pre_2.setStyleSheet("font: 75 12pt \"Times New Roman\";")
        self.label_pre_2.setText("")
        self.label_pre_2.setObjectName("label_pre_2")
        self.line_seg = QtWidgets.QLabel(self.segmentation_box)
        self.line_seg.setGeometry(QtCore.QRect(10, 120, 161, 20))
        self.line_seg.setObjectName("line_seg")
        self.preprocessing_box = QtWidgets.QGroupBox(self.centralwidget)
        self.preprocessing_box.setEnabled(False)
        self.preprocessing_box.setGeometry(QtCore.QRect(180, 10, 171, 201))
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.preprocessing_box.setFont(font)
        self.preprocessing_box.setStyleSheet("background-color: qradialgradient(spread:pad, cx:0.489, cy:0.5, radius:2, fx:0.489, fy:0.494318, stop:0 rgba(255, 119, 224, 255), stop:1 rgba(255, 255, 255, 255));font: italic 14pt \"Monotype Corsiva\";\n"
"\n"
"")
        self.preprocessing_box.setObjectName("preprocessing_box")
        self.shadowremoval = QtWidgets.QCheckBox(self.preprocessing_box)
        self.shadowremoval.setEnabled(False)
        self.shadowremoval.setGeometry(QtCore.QRect(10, 70, 151, 17))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.shadowremoval.setFont(font)
        self.shadowremoval.setStyleSheet("font: 75 12pt \"Times New Roman\";")
        self.shadowremoval.setObjectName("shadowremoval")
        self.hairremoval = QtWidgets.QCheckBox(self.preprocessing_box)
        self.hairremoval.setEnabled(False)
        self.hairremoval.setGeometry(QtCore.QRect(10, 50, 151, 17))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.hairremoval.setFont(font)
        self.hairremoval.setStyleSheet("font: 75 12pt \"Times New Roman\";")
        self.hairremoval.setObjectName("hairremoval")
        self.edgeenhacement = QtWidgets.QCheckBox(self.preprocessing_box)
        self.edgeenhacement.setEnabled(False)
        self.edgeenhacement.setGeometry(QtCore.QRect(10, 30, 151, 17))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.edgeenhacement.setFont(font)
        self.edgeenhacement.setStyleSheet("font: 75 12pt \"Times New Roman\";")
        self.edgeenhacement.setObjectName("edgeenhacement")
        self.applypreprocessing = QtWidgets.QPushButton(self.preprocessing_box)
        self.applypreprocessing.setEnabled(False)
        self.applypreprocessing.setGeometry(QtCore.QRect(90, 170, 75, 23))
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.applypreprocessing.setFont(font)
        self.applypreprocessing.setStyleSheet("color: rgb(0, 0, 0);background-color: qradialgradient(spread:pad, cx:0.489, cy:0.5, radius:2, fx:0.489, fy:0.494318, stop:0 rgba(255, 169, 224, 255), stop:1 rgba(255, 255, 255, 255));font: italic 14pt \"Monotype Corsiva\";\n"
"\n"
"")
        self.applypreprocessing.setObjectName("applypreprocessing")
        self.manualpreprocessing = QtWidgets.QPushButton(self.preprocessing_box)
        self.manualpreprocessing.setEnabled(False)
        self.manualpreprocessing.setGeometry(QtCore.QRect(0, 170, 75, 23))
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.manualpreprocessing.setFont(font)
        self.manualpreprocessing.setStyleSheet("color: rgb(0, 0, 0);background-color: qradialgradient(spread:pad, cx:0.489, cy:0.5, radius:2, fx:0.489, fy:0.494318, stop:0 rgba(255, 169, 224, 255), stop:1 rgba(255, 255, 255, 255));font: italic 14pt \"Monotype Corsiva\";\n"
"\n"
"")
        self.manualpreprocessing.setObjectName("manualpreprocessing")
        self.label_pre = QtWidgets.QLabel(self.preprocessing_box)
        self.label_pre.setEnabled(False)
        self.label_pre.setGeometry(QtCore.QRect(10, 140, 161, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_pre.setFont(font)
        self.label_pre.setStyleSheet("font: 75 12pt \"Times New Roman\";")
        self.label_pre.setText("")
        self.label_pre.setObjectName("label_pre")
        self.line_pre = QtWidgets.QLabel(self.preprocessing_box)
        self.line_pre.setGeometry(QtCore.QRect(10, 110, 151, 20))
        self.line_pre.setObjectName("line_pre")
        self.seg1_2 = QtWidgets.QLabel(self.preprocessing_box)
        self.seg1_2.setEnabled(False)
        self.seg1_2.setGeometry(QtCore.QRect(10, 100, 20, 21))
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.seg1_2.setFont(font)
        self.seg1_2.setObjectName("seg1_2")
        self.pre_bar = QtWidgets.QSlider(self.preprocessing_box)
        self.pre_bar.setEnabled(False)
        self.pre_bar.setGeometry(QtCore.QRect(40, 100, 91, 22))
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.pre_bar.setFont(font)
        self.pre_bar.setOrientation(QtCore.Qt.Horizontal)
        self.pre_bar.setObjectName("pre_bar")
        self.seg2_2 = QtWidgets.QLabel(self.preprocessing_box)
        self.seg2_2.setEnabled(False)
        self.seg2_2.setGeometry(QtCore.QRect(140, 100, 31, 16))
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.seg2_2.setFont(font)
        self.seg2_2.setObjectName("seg2_2")
        self.fullscreen2 = QtWidgets.QPushButton(self.centralwidget)
        self.fullscreen2.setEnabled(False)
        self.fullscreen2.setGeometry(QtCore.QRect(960, 790, 221, 41))
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.fullscreen2.setFont(font)
        self.fullscreen2.setStyleSheet("background-color: qradialgradient(spread:pad, cx:0.489, cy:0.5, radius:1.312, fx:0.472227, fy:0.506, stop:0 rgba(20, 0, 147, 255), stop:1 rgba(255, 255, 255, 255));\n"
"color: rgb(255, 203, 99);font: italic 14pt \"Monotype Corsiva\";")
        self.fullscreen2.setObjectName("fullscreen2")
        self.fig2 = QtWidgets.QGraphicsView(self.centralwidget)
        self.fig2.setEnabled(True)
        self.fig2.setGeometry(QtCore.QRect(740, 250, 701, 531))
        self.fig2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.fig2.setObjectName("fig2")
        self.result_box = QtWidgets.QGroupBox(self.centralwidget)
        self.result_box.setEnabled(False)
        self.result_box.setGeometry(QtCore.QRect(1100, 10, 341, 201))
        self.result_box.setStyleSheet("background-color: rgb(123, 176, 255);font: italic 14pt \"Monotype Corsiva\";")
        self.result_box.setObjectName("result_box")
        self.result_lable = QtWidgets.QLabel(self.result_box)
        self.result_lable.setEnabled(False)
        self.result_lable.setGeometry(QtCore.QRect(170, 170, 161, 21))
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.result_lable.setFont(font)
        self.result_lable.setStyleSheet("color: rgb(0, 0, 0);font: italic 14pt \"Monotype Corsiva\";")
        self.result_lable.setObjectName("result_lable")
        self.scc_2 = QtWidgets.QToolButton(self.result_box)
        self.scc_2.setEnabled(False)
        self.scc_2.setGeometry(QtCore.QRect(80, 150, 61, 31))
        self.scc_2.setStyleSheet("font: italic 14pt \"Monotype Corsiva\";\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(158, 221, 255);")
        self.scc_2.setObjectName("scc_2")
        self.vasc_2 = QtWidgets.QToolButton(self.result_box)
        self.vasc_2.setEnabled(False)
        self.vasc_2.setGeometry(QtCore.QRect(80, 110, 61, 31))
        self.vasc_2.setStyleSheet("font: italic 14pt \"Monotype Corsiva\";\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(158, 221, 255);")
        self.vasc_2.setObjectName("vasc_2")
        self.bk_2 = QtWidgets.QToolButton(self.result_box)
        self.bk_2.setEnabled(False)
        self.bk_2.setGeometry(QtCore.QRect(80, 30, 61, 31))
        self.bk_2.setStyleSheet("font: italic 14pt \"Monotype Corsiva\";\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(158, 221, 255);")
        self.bk_2.setObjectName("bk_2")
        self.bcc_2 = QtWidgets.QToolButton(self.result_box)
        self.bcc_2.setEnabled(False)
        self.bcc_2.setGeometry(QtCore.QRect(0, 110, 71, 31))
        self.bcc_2.setStyleSheet("font: italic 14pt \"Monotype Corsiva\";\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(158, 221, 255);")
        self.bcc_2.setObjectName("bcc_2")
        self.df_2 = QtWidgets.QToolButton(self.result_box)
        self.df_2.setEnabled(False)
        self.df_2.setGeometry(QtCore.QRect(80, 70, 61, 31))
        self.df_2.setStyleSheet("font: italic 14pt \"Monotype Corsiva\";\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(158, 221, 255);")
        self.df_2.setObjectName("df_2")
        self.mel_2 = QtWidgets.QPushButton(self.result_box)
        self.mel_2.setEnabled(False)
        self.mel_2.setGeometry(QtCore.QRect(0, 30, 71, 31))
        self.mel_2.setStyleSheet("font: italic 14pt \"Monotype Corsiva\";\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(158, 221, 255);")
        self.mel_2.setObjectName("mel_2")
        self.nv_2 = QtWidgets.QToolButton(self.result_box)
        self.nv_2.setEnabled(False)
        self.nv_2.setGeometry(QtCore.QRect(0, 70, 71, 31))
        self.nv_2.setStyleSheet("font: italic 14pt \"Monotype Corsiva\";\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(158, 221, 255);")
        self.nv_2.setObjectName("nv_2")
        self.ak_2 = QtWidgets.QToolButton(self.result_box)
        self.ak_2.setEnabled(False)
        self.ak_2.setGeometry(QtCore.QRect(0, 150, 71, 31))
        self.ak_2.setStyleSheet("font: italic 14pt \"Monotype Corsiva\";\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(158, 221, 255);")
        self.ak_2.setObjectName("ak_2")
        self.abcd_4 = QtWidgets.QLabel(self.result_box)
        self.abcd_4.setEnabled(False)
        self.abcd_4.setGeometry(QtCore.QRect(170, 140, 151, 20))
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.abcd_4.setFont(font)
        self.abcd_4.setStyleSheet("color: rgb(0, 0, 0);font: italic 14pt \"Monotype Corsiva\";")
        self.abcd_4.setObjectName("abcd_4")
        self.dateee = QtWidgets.QLabel(self.result_box)
        self.dateee.setEnabled(False)
        self.dateee.setGeometry(QtCore.QRect(160, 20, 161, 101))
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.dateee.setFont(font)
        self.dateee.setStyleSheet("background-color: rgb(123, 176, 255);font: italic 10pt \"Monotype Corsiva\";")
        self.dateee.setText("")
        self.dateee.setObjectName("dateee")
        self.groupBox_1 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_1.setEnabled(True)
        self.groupBox_1.setGeometry(QtCore.QRect(10, 10, 161, 201))
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.groupBox_1.setFont(font)
        self.groupBox_1.setStyleSheet("background-color: qradialgradient(spread:pad, cx:0.495, cy:0.494318, radius:2, fx:0.489, fy:0.494318, stop:0 rgba(221, 32, 56, 255), stop:1 rgba(255, 255, 255, 255));font: italic 12pt \"Monotype Corsiva\";")
        self.groupBox_1.setObjectName("groupBox_1")
        self.cropeimage_2 = QtWidgets.QPushButton(self.groupBox_1)
        self.cropeimage_2.setEnabled(True)
        self.cropeimage_2.setGeometry(QtCore.QRect(10, 120, 141, 24))
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.cropeimage_2.setFont(font)
        self.cropeimage_2.setStyleSheet("color: rgb(0, 0, 0);background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:2, fx:0.5, fy:0.5, stop:0 rgba(240, 101, 142, 237), stop:1 rgba(255, 255, 255, 255));\n"
"font: italic 14pt \"Monotype Corsiva\";")
        self.cropeimage_2.setObjectName("cropeimage_2")
        self.loadimage = QtWidgets.QPushButton(self.groupBox_1)
        self.loadimage.setEnabled(True)
        self.loadimage.setGeometry(QtCore.QRect(10, 30, 141, 24))
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.loadimage.setFont(font)
        self.loadimage.setStyleSheet("color: rgb(0, 0, 0);background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:2, fx:0.5, fy:0.5, stop:0 rgba(240, 101, 142, 237), stop:1 rgba(255, 255, 255, 255));\n"
"font: italic 14pt \"Monotype Corsiva\";")
        self.loadimage.setObjectName("loadimage")
        self.camera = QtWidgets.QPushButton(self.groupBox_1)
        self.camera.setEnabled(True)
        self.camera.setGeometry(QtCore.QRect(10, 70, 141, 24))
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.camera.setFont(font)
        self.camera.setStyleSheet("color: rgb(0, 0, 0);background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:2, fx:0.5, fy:0.5, stop:0 rgba(240, 101, 142, 237), stop:1 rgba(255, 255, 255, 255));\n"
"font: italic 14pt \"Monotype Corsiva\";")
        self.camera.setObjectName("camera")
        self.label = QtWidgets.QLabel(self.groupBox_1)
        self.label.setGeometry(QtCore.QRect(0, 100, 161, 20))
        self.label.setObjectName("label")
        self.cropeimage = QtWidgets.QPushButton(self.groupBox_1)
        self.cropeimage.setEnabled(True)
        self.cropeimage.setGeometry(QtCore.QRect(10, 160, 141, 24))
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.cropeimage.setFont(font)
        self.cropeimage.setStyleSheet("color: rgb(0, 0, 0);background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:2, fx:0.5, fy:0.5, stop:0 rgba(240, 101, 142, 237), stop:1 rgba(255, 255, 255, 255));\n"
"font: italic 14pt \"Monotype Corsiva\";")
        self.cropeimage.setObjectName("cropeimage")
        self.classification_box = QtWidgets.QGroupBox(self.centralwidget)
        self.classification_box.setEnabled(False)
        self.classification_box.setGeometry(QtCore.QRect(910, 10, 181, 201))
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.classification_box.setFont(font)
        self.classification_box.setStyleSheet("background-color: rgb(121, 123, 255);font: italic 14pt \"Monotype Corsiva\";")
        self.classification_box.setObjectName("classification_box")
        self.deepleaning = QtWidgets.QRadioButton(self.classification_box)
        self.deepleaning.setEnabled(False)
        self.deepleaning.setGeometry(QtCore.QRect(10, 20, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.deepleaning.setFont(font)
        self.deepleaning.setStyleSheet("font: 75 12pt \"Times New Roman\";")
        self.deepleaning.setObjectName("deepleaning")
        self.svm = QtWidgets.QRadioButton(self.classification_box)
        self.svm.setEnabled(False)
        self.svm.setGeometry(QtCore.QRect(10, 60, 161, 17))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.svm.setFont(font)
        self.svm.setStyleSheet("font: 75 12pt \"Times New Roman\";")
        self.svm.setObjectName("svm")
        self.KNN = QtWidgets.QRadioButton(self.classification_box)
        self.KNN.setEnabled(False)
        self.KNN.setGeometry(QtCore.QRect(10, 90, 161, 17))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.KNN.setFont(font)
        self.KNN.setStyleSheet("font: 75 12pt \"Times New Roman\";")
        self.KNN.setObjectName("KNN")
        self.label_class = QtWidgets.QLabel(self.classification_box)
        self.label_class.setEnabled(False)
        self.label_class.setGeometry(QtCore.QRect(10, 150, 161, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_class.setFont(font)
        self.label_class.setStyleSheet("font: 75 12pt \"Times New Roman\";")
        self.label_class.setText("")
        self.label_class.setObjectName("label_class")
        self.line_class = QtWidgets.QLabel(self.classification_box)
        self.line_class.setGeometry(QtCore.QRect(0, 110, 181, 20))
        self.line_class.setObjectName("line_class")
        self.applyclassification = QtWidgets.QPushButton(self.classification_box)
        self.applyclassification.setEnabled(False)
        self.applyclassification.setGeometry(QtCore.QRect(20, 170, 151, 23))
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.applyclassification.setFont(font)
        self.applyclassification.setStyleSheet("color: rgb(0, 0, 0);background-color: rgb(171, 173, 255);font: italic 14pt \"Monotype Corsiva\";")
        self.applyclassification.setObjectName("applyclassification")
        self.fullscreen1 = QtWidgets.QPushButton(self.centralwidget)
        self.fullscreen1.setEnabled(False)
        self.fullscreen1.setGeometry(QtCore.QRect(220, 790, 221, 41))
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.fullscreen1.setFont(font)
        self.fullscreen1.setStyleSheet("background-color: qradialgradient(spread:pad, cx:0.489, cy:0.5, radius:1.312, fx:0.472227, fy:0.506, stop:0 rgba(20, 0, 147, 255), stop:1 rgba(255, 255, 255, 255));\n"
"color: rgb(255, 203, 99);font: italic 14pt \"Monotype Corsiva\";")
        self.fullscreen1.setObjectName("fullscreen1")
        self.fig0 = QtWidgets.QGraphicsView(self.centralwidget)
        self.fig0.setEnabled(True)
        self.fig0.setGeometry(QtCore.QRect(0, -30, 1591, 961))
        self.fig0.setStyleSheet("background-color: rgb(255, 215, 221);\n"
"")
        self.fig0.setObjectName("fig0")
        self.clinical_box = QtWidgets.QGroupBox(self.centralwidget)
        self.clinical_box.setEnabled(False)
        self.clinical_box.setGeometry(QtCore.QRect(540, 10, 181, 201))
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.clinical_box.setFont(font)
        self.clinical_box.setStyleSheet("background-color: rgb(194, 133, 255);font: italic 12pt \"Monotype Corsiva\";")
        self.clinical_box.setObjectName("clinical_box")
        self.boundary = QtWidgets.QLabel(self.clinical_box)
        self.boundary.setEnabled(False)
        self.boundary.setGeometry(QtCore.QRect(10, 40, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.boundary.setFont(font)
        self.boundary.setStyleSheet("font: 75 12pt \"Times New Roman\";")
        self.boundary.setObjectName("boundary")
        self.asymetric = QtWidgets.QLabel(self.clinical_box)
        self.asymetric.setEnabled(False)
        self.asymetric.setGeometry(QtCore.QRect(10, 20, 111, 19))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.asymetric.setFont(font)
        self.asymetric.setStyleSheet("font: 75 12pt \"Times New Roman\";")
        self.asymetric.setObjectName("asymetric")
        self.color = QtWidgets.QLabel(self.clinical_box)
        self.color.setEnabled(False)
        self.color.setGeometry(QtCore.QRect(10, 60, 111, 20))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.color.setFont(font)
        self.color.setStyleSheet("font: 75 12pt \"Times New Roman\";")
        self.color.setObjectName("color")
        self.diameter = QtWidgets.QLabel(self.clinical_box)
        self.diameter.setEnabled(False)
        self.diameter.setGeometry(QtCore.QRect(10, 80, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.diameter.setFont(font)
        self.diameter.setStyleSheet("font: 75 12pt \"Times New Roman\";")
        self.diameter.setObjectName("diameter")
        self.diameter1 = QtWidgets.QLabel(self.clinical_box)
        self.diameter1.setEnabled(False)
        self.diameter1.setGeometry(QtCore.QRect(130, 80, 47, 13))
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.diameter1.setFont(font)
        self.diameter1.setObjectName("diameter1")
        self.boundry1 = QtWidgets.QLabel(self.clinical_box)
        self.boundry1.setEnabled(False)
        self.boundry1.setGeometry(QtCore.QRect(130, 40, 47, 16))
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.boundry1.setFont(font)
        self.boundry1.setObjectName("boundry1")
        self.asymetric1 = QtWidgets.QLabel(self.clinical_box)
        self.asymetric1.setEnabled(False)
        self.asymetric1.setGeometry(QtCore.QRect(130, 20, 47, 13))
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.asymetric1.setFont(font)
        self.asymetric1.setObjectName("asymetric1")
        self.color1 = QtWidgets.QLabel(self.clinical_box)
        self.color1.setEnabled(False)
        self.color1.setGeometry(QtCore.QRect(130, 60, 47, 16))
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.color1.setFont(font)
        self.color1.setObjectName("color1")
        self.abcd1 = QtWidgets.QLabel(self.clinical_box)
        self.abcd1.setEnabled(False)
        self.abcd1.setGeometry(QtCore.QRect(120, 120, 51, 20))
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.abcd1.setFont(font)
        self.abcd1.setStyleSheet("font: italic 14pt \"Monotype Corsiva\";")
        self.abcd1.setObjectName("abcd1")
        self.abcd = QtWidgets.QLabel(self.clinical_box)
        self.abcd.setEnabled(False)
        self.abcd.setGeometry(QtCore.QRect(10, 170, 161, 20))
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.abcd.setFont(font)
        self.abcd.setStyleSheet("font: italic 14pt \"Monotype Corsiva\";")
        self.abcd.setObjectName("abcd")
        self.line_abcd = QtWidgets.QLabel(self.clinical_box)
        self.line_abcd.setGeometry(QtCore.QRect(10, 100, 161, 20))
        self.line_abcd.setObjectName("line_abcd")
        self.abcd1_2 = QtWidgets.QLabel(self.clinical_box)
        self.abcd1_2.setEnabled(False)
        self.abcd1_2.setGeometry(QtCore.QRect(10, 140, 171, 20))
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.abcd1_2.setFont(font)
        self.abcd1_2.setStyleSheet("font: italic 14pt \"Monotype Corsiva\";")
        self.abcd1_2.setText("")
        self.abcd1_2.setObjectName("abcd1_2")
        self.abcd1_5 = QtWidgets.QLabel(self.clinical_box)
        self.abcd1_5.setEnabled(False)
        self.abcd1_5.setGeometry(QtCore.QRect(10, 120, 91, 20))
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.abcd1_5.setFont(font)
        self.abcd1_5.setStyleSheet("font: italic 14pt \"Monotype Corsiva\";")
        self.abcd1_5.setObjectName("abcd1_5")
        self.input_box = QtWidgets.QGroupBox(self.centralwidget)
        self.input_box.setEnabled(False)
        self.input_box.setGeometry(QtCore.QRect(730, 10, 181, 201))
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.input_box.setFont(font)
        self.input_box.setStyleSheet("background-color: rgb(152, 111, 255);font: italic 14pt \"Monotype Corsiva\";")
        self.input_box.setObjectName("input_box")
        self.pos1 = QtWidgets.QComboBox(self.input_box)
        self.pos1.setEnabled(False)
        self.pos1.setGeometry(QtCore.QRect(70, 110, 101, 22))
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.pos1.setFont(font)
        self.pos1.setObjectName("pos1")
        self.pos1.addItem("")
        self.pos1.addItem("")
        self.pos1.addItem("")
        self.pos1.addItem("")
        self.pos1.addItem("")
        self.pos1.addItem("")
        self.sex1 = QtWidgets.QComboBox(self.input_box)
        self.sex1.setEnabled(False)
        self.sex1.setGeometry(QtCore.QRect(80, 70, 69, 22))
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.sex1.setFont(font)
        self.sex1.setObjectName("sex1")
        self.sex1.addItem("")
        self.sex1.addItem("")
        self.position_var = QtWidgets.QLabel(self.input_box)
        self.position_var.setEnabled(False)
        self.position_var.setGeometry(QtCore.QRect(10, 110, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.position_var.setFont(font)
        self.position_var.setStyleSheet("font: 75 12pt \"Times New Roman\";")
        self.position_var.setObjectName("position_var")
        self.age_var = QtWidgets.QLabel(self.input_box)
        self.age_var.setEnabled(False)
        self.age_var.setGeometry(QtCore.QRect(10, 20, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.age_var.setFont(font)
        self.age_var.setStyleSheet("font: 75 12pt \"Times New Roman\";")
        self.age_var.setObjectName("age_var")
        self.sex_var = QtWidgets.QLabel(self.input_box)
        self.sex_var.setEnabled(False)
        self.sex_var.setGeometry(QtCore.QRect(10, 70, 61, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.sex_var.setFont(font)
        self.sex_var.setStyleSheet("font: 75 12pt \"Times New Roman\";")
        self.sex_var.setObjectName("sex_var")
        self.applyinputdata = QtWidgets.QPushButton(self.input_box)
        self.applyinputdata.setEnabled(False)
        self.applyinputdata.setGeometry(QtCore.QRect(20, 170, 151, 23))
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.applyinputdata.setFont(font)
        self.applyinputdata.setStyleSheet("color: rgb(0, 0, 0);background-color: rgb(202, 161, 255);font: italic 14pt \"Monotype Corsiva\";")
        self.applyinputdata.setObjectName("applyinputdata")
        self.label_input = QtWidgets.QLabel(self.input_box)
        self.label_input.setEnabled(False)
        self.label_input.setGeometry(QtCore.QRect(10, 140, 161, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_input.setFont(font)
        self.label_input.setStyleSheet("font: 75 12pt \"Times New Roman\";")
        self.label_input.setText("")
        self.label_input.setObjectName("label_input")
        self.age1 = QtWidgets.QSpinBox(self.input_box)
        self.age1.setGeometry(QtCore.QRect(90, 20, 51, 31))
        self.age1.setMinimumSize(QtCore.QSize(0, 31))
        self.age1.setMaximumSize(QtCore.QSize(51, 16777215))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.age1.setFont(font)
        self.age1.setStyleSheet("font: 18pt \"Times New Roman\";")
        self.age1.setObjectName("age1")
        self.original_image = QtWidgets.QPushButton(self.centralwidget)
        self.original_image.setEnabled(False)
        self.original_image.setGeometry(QtCore.QRect(240, 220, 231, 31))
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(True)
        font.setUnderline(True)
        font.setWeight(50)
        self.original_image.setFont(font)
        self.original_image.setStyleSheet("color: rgb(0, 0, 0);background-color: rgb(85, 201, 255);\n"
"font: 75 12pt \"Times New Roman\";\n"
"text-decoration: underline;font: italic 14pt \"Monotype Corsiva\";")
        self.original_image.setAutoDefault(False)
        self.original_image.setObjectName("original_image")
        self.result_image = QtWidgets.QPushButton(self.centralwidget)
        self.result_image.setEnabled(False)
        self.result_image.setGeometry(QtCore.QRect(990, 220, 231, 31))
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(True)
        font.setUnderline(True)
        font.setWeight(50)
        self.result_image.setFont(font)
        self.result_image.setStyleSheet("color: rgb(0, 0, 0);background-color: rgb(85, 201, 255);\n"
"font: 75 12pt \"Times New Roman\";\n"
"text-decoration: underline;font: italic 14pt \"Monotype Corsiva\";")
        self.result_image.setObjectName("result_image")
        self.Author = QtWidgets.QPushButton(self.centralwidget)
        self.Author.setEnabled(True)
        self.Author.setGeometry(QtCore.QRect(740, 830, 711, 31))
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.Author.setFont(font)
        self.Author.setStyleSheet("background-color: qradialgradient(spread:pad, cx:0.489, cy:0.5, radius:1.312, fx:0.472227, fy:0.506, stop:0 rgba(20, 0, 147, 255), stop:1 rgba(255, 255, 255, 255));\n"
"color: rgb(255, 203, 99);font: italic 14pt \"Monotype Corsiva\";")
        self.Author.setObjectName("Author")
        self.fig3 = QtWidgets.QGraphicsView(self.centralwidget)
        self.fig3.setEnabled(True)
        self.fig3.setGeometry(QtCore.QRect(740, 860, 661, 61))
        self.fig3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.fig3.setObjectName("fig3")
        self.fig4 = QtWidgets.QGraphicsView(self.centralwidget)
        self.fig4.setEnabled(True)
        self.fig4.setGeometry(QtCore.QRect(1400, 860, 51, 61))
        self.fig4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.fig4.setObjectName("fig4")
        self.themebox = QtWidgets.QGroupBox(self.centralwidget)
        self.themebox.setEnabled(True)
        self.themebox.setGeometry(QtCore.QRect(0, 840, 731, 91))
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.themebox.setFont(font)
        self.themebox.setStyleSheet("background-color: rgb(214, 163, 255);font: italic 14pt \"Monotype Corsiva\";")
        self.themebox.setObjectName("themebox")
        self.abcd1_3 = QtWidgets.QLabel(self.themebox)
        self.abcd1_3.setEnabled(True)
        self.abcd1_3.setGeometry(QtCore.QRect(120, 170, 41, 20))
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.abcd1_3.setFont(font)
        self.abcd1_3.setStyleSheet("font: italic 14pt \"Monotype Corsiva\";")
        self.abcd1_3.setObjectName("abcd1_3")
        self.abcd_2 = QtWidgets.QLabel(self.themebox)
        self.abcd_2.setEnabled(True)
        self.abcd_2.setGeometry(QtCore.QRect(0, 170, 101, 20))
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.abcd_2.setFont(font)
        self.abcd_2.setStyleSheet("font: italic 14pt \"Monotype Corsiva\";")
        self.abcd_2.setObjectName("abcd_2")
        self.abcd1_4 = QtWidgets.QLabel(self.themebox)
        self.abcd1_4.setEnabled(True)
        self.abcd1_4.setGeometry(QtCore.QRect(10, 130, 131, 20))
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.abcd1_4.setFont(font)
        self.abcd1_4.setStyleSheet("font: italic 14pt \"Monotype Corsiva\";")
        self.abcd1_4.setText("")
        self.abcd1_4.setObjectName("abcd1_4")
        self.ThemeComboBox = QtWidgets.QComboBox(self.themebox)
        self.ThemeComboBox.setEnabled(True)
        self.ThemeComboBox.setGeometry(QtCore.QRect(10, 30, 91, 28))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.ThemeComboBox.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.ThemeComboBox.setFont(font)
        self.ThemeComboBox.setFocusPolicy(QtCore.Qt.NoFocus)
        self.ThemeComboBox.setStyleSheet("background-color: rgb(85, 170, 255);\n"
"font: italic 14pt \"Monotype Corsiva\";")
        self.ThemeComboBox.setObjectName("ThemeComboBox")
        self.ThemeComboBox.addItem("")
        self.ThemeComboBox.addItem("")
        self.ThemeComboBox.addItem("")
        self.pushButtonColor1 = QtWidgets.QPushButton(self.themebox)
        self.pushButtonColor1.setGeometry(QtCore.QRect(150, 30, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(True)
        font.setUnderline(True)
        font.setWeight(50)
        self.pushButtonColor1.setFont(font)
        self.pushButtonColor1.setStyleSheet("background-color: rgb(85, 170, 255);\n"
"font: italic 14pt \"Monotype Corsiva\";")
        self.pushButtonColor1.setObjectName("pushButtonColor1")
        self.pushButtonColor2 = QtWidgets.QPushButton(self.themebox)
        self.pushButtonColor2.setGeometry(QtCore.QRect(330, 30, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(True)
        font.setUnderline(True)
        font.setWeight(50)
        self.pushButtonColor2.setFont(font)
        self.pushButtonColor2.setStyleSheet("background-color: rgb(85, 170, 255);\n"
"font: italic 14pt \"Monotype Corsiva\";")
        self.pushButtonColor2.setObjectName("pushButtonColor2")
        self.author_7 = QtWidgets.QPushButton(self.themebox)
        self.author_7.setEnabled(True)
        self.author_7.setGeometry(QtCore.QRect(150, 20, 261, 51))
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(True)
        font.setUnderline(True)
        font.setWeight(50)
        self.author_7.setFont(font)
        self.author_7.setStyleSheet("background-color: rgb(85, 201, 255);\n"
"font: 75 12pt \"Times New Roman\";\n"
"text-decoration: underline;font: italic 14pt \"Monotype Corsiva\";")
        self.author_7.setObjectName("author_7")
        self.languageComboBox = QtWidgets.QComboBox(self.themebox)
        self.languageComboBox.setEnabled(True)
        self.languageComboBox.setGeometry(QtCore.QRect(420, 20, 111, 28))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.languageComboBox.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.languageComboBox.setFont(font)
        self.languageComboBox.setFocusPolicy(QtCore.Qt.NoFocus)
        self.languageComboBox.setStyleSheet("background-color: rgb(85, 170, 255);\n"
"font: italic 14pt \"Monotype Corsiva\";")
        self.languageComboBox.setObjectName("languageComboBox")
        self.languageComboBox.addItem("")
        self.languageComboBox.addItem("")
        self.languageComboBox.addItem("")
        self.languageComboBox.addItem("")
        self.languageComboBox.addItem("")
        self.languageComboBox.addItem("")
        self.languageComboBox.addItem("")
        self.languageComboBox.addItem("")
        self.languageComboBox.addItem("")
        self.languageComboBox.addItem("")
        self.languageComboBox.addItem("")
        self.languageComboBox.addItem("")
        self.pushButtonFont = QtWidgets.QPushButton(self.themebox)
        self.pushButtonFont.setGeometry(QtCore.QRect(650, 30, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(True)
        font.setUnderline(True)
        font.setWeight(50)
        self.pushButtonFont.setFont(font)
        self.pushButtonFont.setStyleSheet("background-color: rgb(85, 170, 255);\n"
"font: italic 14pt \"Monotype Corsiva\";")
        self.pushButtonFont.setObjectName("pushButtonFont")
        self.pushButtonLanguage = QtWidgets.QPushButton(self.themebox)
        self.pushButtonLanguage.setGeometry(QtCore.QRect(420, 50, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(True)
        font.setUnderline(True)
        font.setWeight(50)
        self.pushButtonLanguage.setFont(font)
        self.pushButtonLanguage.setStyleSheet("background-color: rgb(85, 170, 255);\n"
"font: italic 14pt \"Monotype Corsiva\";")
        self.pushButtonLanguage.setObjectName("pushButtonLanguage")
        self.pushButtonTheme = QtWidgets.QPushButton(self.themebox)
        self.pushButtonTheme.setGeometry(QtCore.QRect(100, 30, 41, 31))
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButtonTheme.setFont(font)
        self.pushButtonTheme.setStyleSheet("background-color: rgb(85, 170, 255);\n"
"font:  14pt \"Monotype Corsiva\";")
        self.pushButtonTheme.setObjectName("pushButtonTheme")
        self.fig30 = QtWidgets.QGraphicsView(self.themebox)
        self.fig30.setEnabled(True)
        self.fig30.setGeometry(QtCore.QRect(530, 10, 111, 81))
        self.fig30.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.fig30.setObjectName("fig30")
        self.author_7.raise_()
        self.abcd1_3.raise_()
        self.abcd_2.raise_()
        self.abcd1_4.raise_()
        self.ThemeComboBox.raise_()
        self.pushButtonColor1.raise_()
        self.pushButtonColor2.raise_()
        self.languageComboBox.raise_()
        self.pushButtonFont.raise_()
        self.pushButtonLanguage.raise_()
        self.pushButtonTheme.raise_()
        self.fig30.raise_()
        self.status = QtWidgets.QPushButton(self.centralwidget)
        self.status.setEnabled(True)
        self.status.setGeometry(QtCore.QRect(740, 860, 211, 61))
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(True)
        font.setUnderline(True)
        font.setWeight(50)
        self.status.setFont(font)
        self.status.setStyleSheet("background-color: rgb(85, 201, 255);\n"
"font: 75 12pt \"Times New Roman\";\n"
"text-decoration: underline;font: italic 14pt \"Monotype Corsiva\";")
        self.status.setAutoDefault(False)
        self.status.setObjectName("status")
        self.seg_text1 = QtWidgets.QLabel(self.centralwidget)
        self.seg_text1.setEnabled(False)
        self.seg_text1.setGeometry(QtCore.QRect(450, 800, 20, 21))
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.seg_text1.setFont(font)
        self.seg_text1.setStyleSheet("background-color:  rgb(255, 215, 221);")
        self.seg_text1.setObjectName("seg_text1")
        self.zoom_bar_1 = QtWidgets.QSlider(self.centralwidget)
        self.zoom_bar_1.setEnabled(True)
        self.zoom_bar_1.setGeometry(QtCore.QRect(480, 800, 91, 22))
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.zoom_bar_1.setFont(font)
        self.zoom_bar_1.setStyleSheet("background-color:  rgb(255, 215, 221);")
        self.zoom_bar_1.setOrientation(QtCore.Qt.Horizontal)
        self.zoom_bar_1.setObjectName("zoom_bar_1")
        self.seg_text2 = QtWidgets.QLabel(self.centralwidget)
        self.seg_text2.setEnabled(False)
        self.seg_text2.setGeometry(QtCore.QRect(580, 800, 31, 16))
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.seg_text2.setFont(font)
        self.seg_text2.setStyleSheet("background-color: rgb(255, 215, 221);")
        self.seg_text2.setObjectName("seg_text2")
        self.zoom_bar_2 = QtWidgets.QSlider(self.centralwidget)
        self.zoom_bar_2.setEnabled(True)
        self.zoom_bar_2.setGeometry(QtCore.QRect(1230, 800, 91, 22))
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.zoom_bar_2.setFont(font)
        self.zoom_bar_2.setStyleSheet("background-color: rgb(255, 215, 221);")
        self.zoom_bar_2.setOrientation(QtCore.Qt.Horizontal)
        self.zoom_bar_2.setObjectName("zoom_bar_2")
        self.seg_text4 = QtWidgets.QLabel(self.centralwidget)
        self.seg_text4.setEnabled(False)
        self.seg_text4.setGeometry(QtCore.QRect(1330, 800, 31, 16))
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.seg_text4.setFont(font)
        self.seg_text4.setStyleSheet("background-color: rgb(255, 215, 221);")
        self.seg_text4.setObjectName("seg_text4")
        self.seg_text3 = QtWidgets.QLabel(self.centralwidget)
        self.seg_text3.setEnabled(False)
        self.seg_text3.setGeometry(QtCore.QRect(1200, 800, 20, 21))
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.seg_text3.setFont(font)
        self.seg_text3.setStyleSheet("background-color: rgb(255, 215, 221);")
        self.seg_text3.setObjectName("seg_text3")
        self.label_zoom1 = QtWidgets.QLabel(self.centralwidget)
        self.label_zoom1.setEnabled(False)
        self.label_zoom1.setGeometry(QtCore.QRect(620, 800, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_zoom1.setFont(font)
        self.label_zoom1.setStyleSheet("font: 75 12pt \"Times New Roman\";background-color: rgb(255, 215, 221);")
        self.label_zoom1.setText("")
        self.label_zoom1.setObjectName("label_zoom1")
        self.label_zoom2 = QtWidgets.QLabel(self.centralwidget)
        self.label_zoom2.setEnabled(False)
        self.label_zoom2.setGeometry(QtCore.QRect(1350, 800, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_zoom2.setFont(font)
        self.label_zoom2.setStyleSheet("font: 75 12pt \"Times New Roman\";background-color: rgb(255, 215, 221);")
        self.label_zoom2.setText("")
        self.label_zoom2.setObjectName("label_zoom2")
        self.saveimage = QtWidgets.QPushButton(self.centralwidget)
        self.saveimage.setEnabled(True)
        self.saveimage.setGeometry(QtCore.QRect(20, 800, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.saveimage.setFont(font)
        self.saveimage.setStyleSheet("color: rgb(0, 0, 0);background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:2, fx:0.5, fy:0.5, stop:0 rgba(240, 101, 142, 237), stop:1 rgba(255, 255, 255, 255));\n"
"font: italic 14pt \"Monotype Corsiva\";")
        self.saveimage.setObjectName("saveimage")
        self.saveimage_2 = QtWidgets.QPushButton(self.centralwidget)
        self.saveimage_2.setEnabled(True)
        self.saveimage_2.setGeometry(QtCore.QRect(740, 800, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.saveimage_2.setFont(font)
        self.saveimage_2.setStyleSheet("color: rgb(0, 0, 0);background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:2, fx:0.5, fy:0.5, stop:0 rgba(240, 101, 142, 237), stop:1 rgba(255, 255, 255, 255));\n"
"font: italic 14pt \"Monotype Corsiva\";")
        self.saveimage_2.setObjectName("saveimage_2")
        self.time1 = QtWidgets.QPushButton(self.centralwidget)
        self.time1.setEnabled(False)
        self.time1.setGeometry(QtCore.QRect(20, 220, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(True)
        font.setUnderline(True)
        font.setWeight(50)
        self.time1.setFont(font)
        self.time1.setStyleSheet("background-color: rgb(85,201, 25);\n"
"font: 75 12pt \"Times New Roman\";\n"
"text-decoration: underline;font: italic 14pt \"Monotype Corsiva\";\n"
"\n"
"\n"
"color: rgb(0, 0, 0);\n"
"")
        self.time1.setObjectName("time1")
        self.time2 = QtWidgets.QPushButton(self.centralwidget)
        self.time2.setEnabled(False)
        self.time2.setGeometry(QtCore.QRect(1330, 220, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(True)
        font.setUnderline(True)
        font.setWeight(50)
        self.time2.setFont(font)
        self.time2.setStyleSheet("background-color: rgb(85,201, 25);\n"
"color: rgb(0, 0, 0);\n"
"font: 75 12pt \"Times New Roman\";\n"
"text-decoration: underline;font: italic 14pt \"Monotype Corsiva\";")
        self.time2.setObjectName("time2")
        self.fig0.raise_()
        self.segmentation_box.raise_()
        self.preprocessing_box.raise_()
        self.fig2.raise_()
        self.groupBox_1.raise_()
        self.classification_box.raise_()
        self.fig1.raise_()
        self.result_box.raise_()
        self.clinical_box.raise_()
        self.input_box.raise_()
        self.original_image.raise_()
        self.result_image.raise_()
        self.fullscreen1.raise_()
        self.fullscreen2.raise_()
        self.Author.raise_()
        self.fig3.raise_()
        self.fig4.raise_()
        self.themebox.raise_()
        self.status.raise_()
        self.seg_text1.raise_()
        self.zoom_bar_1.raise_()
        self.seg_text2.raise_()
        self.zoom_bar_2.raise_()
        self.seg_text4.raise_()
        self.seg_text3.raise_()
        self.label_zoom1.raise_()
        self.label_zoom2.raise_()
        self.saveimage.raise_()
        self.saveimage_2.raise_()
        self.time1.raise_()
        self.time2.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1462, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menupreprocessing = QtWidgets.QMenu(self.menubar)
        self.menupreprocessing.setObjectName("menupreprocessing")
        self.menuSegmentation = QtWidgets.QMenu(self.menubar)
        self.menuSegmentation.setObjectName("menuSegmentation")
        self.menuinput_data = QtWidgets.QMenu(self.menubar)
        self.menuinput_data.setObjectName("menuinput_data")
        self.menuClassification = QtWidgets.QMenu(self.menubar)
        self.menuClassification.setObjectName("menuClassification")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuabout_us = QtWidgets.QMenu(self.menuHelp)
        self.menuabout_us.setObjectName("menuabout_us")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionloadimage = QtWidgets.QAction(MainWindow)
        self.actionloadimage.setObjectName("actionloadimage")
        self.actioncamera = QtWidgets.QAction(MainWindow)
        self.actioncamera.setObjectName("actioncamera")
        self.actioncrop = QtWidgets.QAction(MainWindow)
        self.actioncrop.setObjectName("actioncrop")
        self.actionsaveimage = QtWidgets.QAction(MainWindow)
        self.actionsaveimage.setObjectName("actionsaveimage")
        self.actionshadowremoval = QtWidgets.QAction(MainWindow)
        self.actionshadowremoval.setObjectName("actionshadowremoval")
        self.actionhairremoval = QtWidgets.QAction(MainWindow)
        self.actionhairremoval.setObjectName("actionhairremoval")
        self.actionedgenhecement = QtWidgets.QAction(MainWindow)
        self.actionedgenhecement.setObjectName("actionedgenhecement")
        self.actionEntropy = QtWidgets.QAction(MainWindow)
        self.actionEntropy.setObjectName("actionEntropy")
        self.actionThershold = QtWidgets.QAction(MainWindow)
        self.actionThershold.setObjectName("actionThershold")
        self.actionage = QtWidgets.QAction(MainWindow)
        self.actionage.setObjectName("actionage")
        self.actionsex = QtWidgets.QAction(MainWindow)
        self.actionsex.setObjectName("actionsex")
        self.actionposition = QtWidgets.QAction(MainWindow)
        self.actionposition.setObjectName("actionposition")
        self.actionDeepLearning = QtWidgets.QAction(MainWindow)
        self.actionDeepLearning.setObjectName("actionDeepLearning")
        self.actionSVM = QtWidgets.QAction(MainWindow)
        self.actionSVM.setObjectName("actionSVM")
        self.actionKNN = QtWidgets.QAction(MainWindow)
        self.actionKNN.setObjectName("actionKNN")
        self.actionHelp_Software = QtWidgets.QAction(MainWindow)
        self.actionHelp_Software.setObjectName("actionHelp_Software")
        self.actionvisit_Out_site = QtWidgets.QAction(MainWindow)
        self.actionvisit_Out_site.setObjectName("actionvisit_Out_site")
        self.actionVisit_software_page = QtWidgets.QAction(MainWindow)
        self.actionVisit_software_page.setObjectName("actionVisit_software_page")
        self.actionLicence = QtWidgets.QAction(MainWindow)
        self.actionLicence.setObjectName("actionLicence")
        self.menuFile.addAction(self.actionloadimage)
        self.menuFile.addAction(self.actioncamera)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actioncrop)
        self.menuFile.addAction(self.actionsaveimage)
        self.menupreprocessing.addAction(self.actionshadowremoval)
        self.menupreprocessing.addAction(self.actionhairremoval)
        self.menupreprocessing.addAction(self.actionedgenhecement)
        self.menuSegmentation.addAction(self.actionEntropy)
        self.menuSegmentation.addAction(self.actionThershold)
        self.menuinput_data.addAction(self.actionage)
        self.menuinput_data.addAction(self.actionsex)
        self.menuinput_data.addAction(self.actionposition)
        self.menuClassification.addAction(self.actionDeepLearning)
        self.menuClassification.addAction(self.actionSVM)
        self.menuClassification.addAction(self.actionKNN)
        self.menuabout_us.addSeparator()
        self.menuabout_us.addAction(self.actionvisit_Out_site)
        self.menuabout_us.addAction(self.actionVisit_software_page)
        self.menuHelp.addAction(self.menuabout_us.menuAction())
        self.menuHelp.addAction(self.actionHelp_Software)
        self.menuHelp.addAction(self.actionLicence)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menupreprocessing.menuAction())
        self.menubar.addAction(self.menuSegmentation.menuAction())
        self.menubar.addAction(self.menuinput_data.menuAction())
        self.menubar.addAction(self.menuClassification.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.segmentation_box.setTitle(_translate("MainWindow", "Segmentation"))
        self.entropymethod.setText(_translate("MainWindow", "Entropy  Method"))
        self.thersholdmethod.setText(_translate("MainWindow", "Threshold Method"))
        self.applysegmentation.setText(_translate("MainWindow", "Apply"))
        self.seg1.setText(_translate("MainWindow", "0"))
        self.seg2.setText(_translate("MainWindow", "255"))
        self.manualsegmentation.setText(_translate("MainWindow", "Manual"))
        self.line_seg.setText(_translate("MainWindow", "------------------------------"))
        self.preprocessing_box.setTitle(_translate("MainWindow", "Preprocessing"))
        self.shadowremoval.setText(_translate("MainWindow", "Shadow Removal"))
        self.hairremoval.setText(_translate("MainWindow", "Hair Removal"))
        self.edgeenhacement.setText(_translate("MainWindow", "Edge Enhancement"))
        self.applypreprocessing.setText(_translate("MainWindow", "Apply"))
        self.manualpreprocessing.setText(_translate("MainWindow", "Manual"))
        self.line_pre.setText(_translate("MainWindow", "---------------------------------"))
        self.seg1_2.setText(_translate("MainWindow", "0"))
        self.seg2_2.setText(_translate("MainWindow", "255"))
        self.fullscreen2.setText(_translate("MainWindow", "Full Screen"))
        self.result_box.setTitle(_translate("MainWindow", "Result"))
        self.result_lable.setText(_translate("MainWindow", "Result"))
        self.scc_2.setText(_translate("MainWindow", "SCC"))
        self.vasc_2.setText(_translate("MainWindow", "VASC"))
        self.bk_2.setText(_translate("MainWindow", "BKL"))
        self.bcc_2.setText(_translate("MainWindow", "BCC"))
        self.df_2.setText(_translate("MainWindow", "DF"))
        self.mel_2.setText(_translate("MainWindow", "Mel"))
        self.nv_2.setText(_translate("MainWindow", "NV"))
        self.ak_2.setText(_translate("MainWindow", "AK"))
        self.abcd_4.setText(_translate("MainWindow", "Result"))
        self.groupBox_1.setTitle(_translate("MainWindow", "Input  image "))
        self.cropeimage_2.setText(_translate("MainWindow", "Zoom"))
        self.loadimage.setText(_translate("MainWindow", "Load Image"))
        self.camera.setText(_translate("MainWindow", "Camera"))
        self.label.setText(_translate("MainWindow", "--------------------------------------"))
        self.cropeimage.setText(_translate("MainWindow", "Crop"))
        self.classification_box.setTitle(_translate("MainWindow", "Classification"))
        self.deepleaning.setText(_translate("MainWindow", "Deep Learning "))
        self.svm.setText(_translate("MainWindow", "SVM on Deep features"))
        self.KNN.setText(_translate("MainWindow", "KNN on Deep features"))
        self.line_class.setText(_translate("MainWindow", "------------------------------------------------"))
        self.applyclassification.setText(_translate("MainWindow", "Apply"))
        self.fullscreen1.setText(_translate("MainWindow", "Full Screen"))
        self.clinical_box.setTitle(_translate("MainWindow", "Clinical Method (ABCD)"))
        self.boundary.setText(_translate("MainWindow", "Boundary"))
        self.asymetric.setText(_translate("MainWindow", "Asymmetric"))
        self.color.setText(_translate("MainWindow", "Color"))
        self.diameter.setText(_translate("MainWindow", "Diameter"))
        self.diameter1.setText(_translate("MainWindow", "D"))
        self.boundry1.setText(_translate("MainWindow", "B"))
        self.asymetric1.setText(_translate("MainWindow", "A"))
        self.color1.setText(_translate("MainWindow", "C"))
        self.abcd1.setText(_translate("MainWindow", "Score"))
        self.abcd.setText(_translate("MainWindow", "ABCD Result"))
        self.line_abcd.setText(_translate("MainWindow", "--------------------------------"))
        self.abcd1_5.setText(_translate("MainWindow", "Sum  Score:"))
        self.input_box.setTitle(_translate("MainWindow", "Input data"))
        self.pos1.setItemText(0, _translate("MainWindow", "Anterior Torso"))
        self.pos1.setItemText(1, _translate("MainWindow", "Posterior Torso"))
        self.pos1.setItemText(2, _translate("MainWindow", "Upper Extremity"))
        self.pos1.setItemText(3, _translate("MainWindow", "Lower Extremity"))
        self.pos1.setItemText(4, _translate("MainWindow", "Head/Neck"))
        self.pos1.setItemText(5, _translate("MainWindow", "Palms/Soles"))
        self.sex1.setItemText(0, _translate("MainWindow", "Male"))
        self.sex1.setItemText(1, _translate("MainWindow", "Female"))
        self.position_var.setText(_translate("MainWindow", "Position"))
        self.age_var.setText(_translate("MainWindow", "Age"))
        self.sex_var.setText(_translate("MainWindow", "Sex"))
        self.applyinputdata.setText(_translate("MainWindow", "Apply"))
        self.original_image.setText(_translate("MainWindow", "Original Image"))
        self.result_image.setText(_translate("MainWindow", "Result Image"))
        self.Author.setText(_translate("MainWindow", "Created by Alireza Zahedi    Tarbiat Moderes University     Version 2 , 2023"))
        self.themebox.setTitle(_translate("MainWindow", "Theme"))
        self.abcd1_3.setText(_translate("MainWindow", "Score"))
        self.abcd_2.setText(_translate("MainWindow", "ABCD Result"))
        self.ThemeComboBox.setItemText(0, _translate("MainWindow", "Dark"))
        self.ThemeComboBox.setItemText(1, _translate("MainWindow", "Bright"))
        self.ThemeComboBox.setItemText(2, _translate("MainWindow", "Default"))
        self.pushButtonColor1.setText(_translate("MainWindow", "Background"))
        self.pushButtonColor2.setText(_translate("MainWindow", "Boxes"))
        self.author_7.setText(_translate("MainWindow", "     Color"))
        self.languageComboBox.setItemText(0, _translate("MainWindow", "English"))
        self.languageComboBox.setItemText(1, _translate("MainWindow", "فارسی"))
        self.languageComboBox.setItemText(2, _translate("MainWindow", "French"))
        self.languageComboBox.setItemText(3, _translate("MainWindow", "Germany"))
        self.languageComboBox.setItemText(4, _translate("MainWindow", "Hindustani "))
        self.languageComboBox.setItemText(5, _translate("MainWindow", "Chinese "))
        self.languageComboBox.setItemText(6, _translate("MainWindow", "Spanish "))
        self.languageComboBox.setItemText(7, _translate("MainWindow", "العربیه"))
        self.languageComboBox.setItemText(8, _translate("MainWindow", "Malay "))
        self.languageComboBox.setItemText(9, _translate("MainWindow", "Russian "))
        self.languageComboBox.setItemText(10, _translate("MainWindow", "Italy"))
        self.languageComboBox.setItemText(11, _translate("MainWindow", "Dutch"))
        self.pushButtonFont.setText(_translate("MainWindow", "Font"))
        self.pushButtonLanguage.setText(_translate("MainWindow", "Language"))
        self.pushButtonTheme.setText(_translate("MainWindow", "done"))
        self.status.setText(_translate("MainWindow", "status"))
        self.seg_text1.setText(_translate("MainWindow", "0.1"))
        self.seg_text2.setText(_translate("MainWindow", "4"))
        self.seg_text4.setText(_translate("MainWindow", "4"))
        self.seg_text3.setText(_translate("MainWindow", "0.1"))
        self.saveimage.setText(_translate("MainWindow", "Save Image"))
        self.saveimage_2.setText(_translate("MainWindow", "Save Image"))
        self.time1.setText(_translate("MainWindow", "Time"))
        self.time2.setText(_translate("MainWindow", "Time"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menupreprocessing.setTitle(_translate("MainWindow", "Preprocessing"))
        self.menuSegmentation.setTitle(_translate("MainWindow", "Segmentation"))
        self.menuinput_data.setTitle(_translate("MainWindow", "Input data"))
        self.menuClassification.setTitle(_translate("MainWindow", "Classification"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.menuabout_us.setTitle(_translate("MainWindow", "about us"))
        self.actionloadimage.setText(_translate("MainWindow", "Load Image"))
        self.actionloadimage.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actioncamera.setText(_translate("MainWindow", "Camera"))
        self.actioncamera.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actioncrop.setText(_translate("MainWindow", "Crop"))
        self.actionsaveimage.setText(_translate("MainWindow", "Save Image"))
        self.actionshadowremoval.setText(_translate("MainWindow", "Shadow Removal"))
        self.actionhairremoval.setText(_translate("MainWindow", "Hair Removal"))
        self.actionedgenhecement.setText(_translate("MainWindow", "Edge Enhecement"))
        self.actionEntropy.setText(_translate("MainWindow", "Entropy"))
        self.actionThershold.setText(_translate("MainWindow", "Thershold"))
        self.actionage.setText(_translate("MainWindow", "Age"))
        self.actionsex.setText(_translate("MainWindow", "Sex"))
        self.actionposition.setText(_translate("MainWindow", "Position"))
        self.actionDeepLearning.setText(_translate("MainWindow", "Deep Learning"))
        self.actionSVM.setText(_translate("MainWindow", "SVM on Deep features"))
        self.actionKNN.setText(_translate("MainWindow", "KNN  on Deep features"))
        self.actionHelp_Software.setText(_translate("MainWindow", "Help Software"))
        self.actionvisit_Out_site.setText(_translate("MainWindow", "Visit Our site"))
        self.actionVisit_software_page.setText(_translate("MainWindow", "Visit software page"))
        self.actionLicence.setText(_translate("MainWindow", "Licence"))

